artifact_location: /workspaces/Howler-Monkey/'https:/dagshub.com/GMainardi/Howler-Monkey.mlflow'/0
creation_time: 1713555637563
experiment_id: '0'
last_update_time: 1713555637563
lifecycle_stage: active
name: Default
