stages:
  data_ingestion:
    cmd: python src/HowlerMonkey/pipeline/stage_01_data_ingestion.py
    deps:
      - src/HowlerMonkey/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      - config/coco.yaml
    outs:
      - artifacts/data_ingestion/data


  training:
    cmd: python src/HowlerMonkey/pipeline/stage_02_model_training.py
    deps:
      - src/HowlerMonkey/pipeline/stage_02_model_training.py
      - config/config.yaml
      - config/coco.yaml
      - artifacts/data_ingestion/data
    params:
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/training/best.pt


  evaluation:
    cmd: python src/HowlerMonkey/pipeline/stage_03_model_evaluation.py
    deps:
      - src/HowlerMonkey/pipeline/stage_03_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/training/best.pt
      - config/coco.yaml
    params:
      - EPOCHS
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false