artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  data_id: 17nILb0XH7TQIzdL8IafcGSEOgihGgSAe
  local_data_file: artifacts/data_ingestion/howler_data.zip
  unzip_dir: artifacts/data_ingestion

training:
  root_dir: artifacts/training
  model_path: artifacts/training/yolov8n.pt
  data_file_path: config/coco.yaml

