artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_id: 15IcJEbi8o5IfjYOcYX45htqitGJKkO6X
  local_data_file: artifacts/data_ingestion/howler_data.zip
  unzip_dir: artifacts/data_ingestion

training:
  root_dir: artifacts/training
  model_path: artifacts/training/yolov8n.pt
  data_file_path: config/coco.yaml

predicting:
  root_dir: artifacts/predicting
  prediction_output: artifacts/predicting/output.mp4