artifact_location: /workspaces/Howler-Monkey/'https:/dagshub.com/GMainardi/Howler-Monkey.mlflow'/382641981569216505
creation_time: 1713555637572
experiment_id: '382641981569216505'
last_update_time: 1713555637572
lifecycle_stage: active
name: artifacts/training
