name: Docker base Image CI for GHCR

on:
  push
    #paths:
    #  - .github/.devcontainer/**


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v4
    - 
      name: Convert actor name to lower case
        un: echo "GITHUB_ACTOR=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GH_PAT }}
    - 
        name: Pre-build dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}
          push: always
